### ISSUE TITLE
Spring Boot update to 2.7

### ISSUE THREAD

**Issue by kraluk** [jvm-bloggers/jvm-bloggers#738]
Spring Boot since version `2.7.0` has started providing a new version of the `h2` in-memory database which we're using in integration tests.

Unfortunately, `h2` in version 2 has introduced a lot of breaking changes (i.e. new keywords like `VALUE` - that we are using in naming our DB columns) and due to them, our project's tests are failing quite significantly (especially integration ones).

What's even worse, there are some issues with `liquibase` as well - especially when mentioned above errors are occurring.

And staying with the `h2` v1 would not be a good idea in long term - as this version has several security issues.

We have to figure out how we should migrate to `h2` v2 or try to plan using a different approach in our tests (`testcontainers` perhaps?) - when all issues will be identified, they should be discussed. Hopefully, it will be a good discussion starter.

[0] https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#h2-21
[1] https://h2database.com/html/migration-to-v2.html
[2] https://stackoverflow.com/questions/72361477/spring-boot-2-7-0-liquibase-fails-with-migration-files-for-change-set
[3] https://groups.google.com/g/h2-database/c/yxnv64Ak-u8
[4] https://groups.google.com/g/h2-database/c/naveVfPQU_A

**Comment by kraluk** [comment]
I guess I'll try to figure out some solution here - bumping up Spring Boot version will be always desired, I think :)

**Comment by kraluk** [comment]
Just for documentation purposes.

`h2` has to be reconfigured and set to the compatibility mode of PostgreSQL and Hibernate's dialect has to be set explicitly (`application-test.yaml`):

```yaml
spring:
  datasource:
    url: "jdbc:h2:mem:test-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=VALUE,value,month,year"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
```
